/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.I18nProductSeo;
import java.io.IOException;

/**
 * I18nProduct
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T13:53:33.030Z")
public class I18nProduct {
  @SerializedName("locale")
  private String locale = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("synopsis")
  private String synopsis = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("characteristics")
  private String characteristics = null;

  @SerializedName("seo")
  private I18nProductSeo seo = null;

  public I18nProduct locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  @ApiModelProperty(example = "pt_PT", required = true, value = "")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public I18nProduct name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public I18nProduct synopsis(String synopsis) {
    this.synopsis = synopsis;
    return this;
  }

   /**
   * Get synopsis
   * @return synopsis
  **/
  @ApiModelProperty(value = "")
  public String getSynopsis() {
    return synopsis;
  }

  public void setSynopsis(String synopsis) {
    this.synopsis = synopsis;
  }

  public I18nProduct description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "Description of product", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public I18nProduct characteristics(String characteristics) {
    this.characteristics = characteristics;
    return this;
  }

   /**
   * Get characteristics
   * @return characteristics
  **/
  @ApiModelProperty(example = "Characteristics of product", value = "")
  public String getCharacteristics() {
    return characteristics;
  }

  public void setCharacteristics(String characteristics) {
    this.characteristics = characteristics;
  }

  public I18nProduct seo(I18nProductSeo seo) {
    this.seo = seo;
    return this;
  }

   /**
   * Get seo
   * @return seo
  **/
  @ApiModelProperty(value = "")
  public I18nProductSeo getSeo() {
    return seo;
  }

  public void setSeo(I18nProductSeo seo) {
    this.seo = seo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    I18nProduct i18nProduct = (I18nProduct) o;
    return Objects.equals(this.locale, i18nProduct.locale) &&
        Objects.equals(this.name, i18nProduct.name) &&
        Objects.equals(this.synopsis, i18nProduct.synopsis) &&
        Objects.equals(this.description, i18nProduct.description) &&
        Objects.equals(this.characteristics, i18nProduct.characteristics) &&
        Objects.equals(this.seo, i18nProduct.seo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locale, name, synopsis, description, characteristics, seo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class I18nProduct {\n");
    
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    synopsis: ").append(toIndentedString(synopsis)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    characteristics: ").append(toIndentedString(characteristics)).append("\n");
    sb.append("    seo: ").append(toIndentedString(seo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

