/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MetaPartialResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T13:53:33.030Z")
public class MetaPartialResponse {
  @SerializedName("first_page_url")
  private String firstPageUrl = null;

  @SerializedName("last_page_url")
  private String lastPageUrl = null;

  @SerializedName("next_page_url")
  private String nextPageUrl = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("prev_page_url")
  private String prevPageUrl = null;

  public MetaPartialResponse firstPageUrl(String firstPageUrl) {
    this.firstPageUrl = firstPageUrl;
    return this;
  }

   /**
   * Get firstPageUrl
   * @return firstPageUrl
  **/
  @ApiModelProperty(example = "http://api.facestore.pt/v1/categories?order_by=id%2Cdesc&page=1", value = "")
  public String getFirstPageUrl() {
    return firstPageUrl;
  }

  public void setFirstPageUrl(String firstPageUrl) {
    this.firstPageUrl = firstPageUrl;
  }

  public MetaPartialResponse lastPageUrl(String lastPageUrl) {
    this.lastPageUrl = lastPageUrl;
    return this;
  }

   /**
   * Get lastPageUrl
   * @return lastPageUrl
  **/
  @ApiModelProperty(example = "http://api.facestore.pt/v1/categories?order_by=id%2Cdesc&page=4", value = "")
  public String getLastPageUrl() {
    return lastPageUrl;
  }

  public void setLastPageUrl(String lastPageUrl) {
    this.lastPageUrl = lastPageUrl;
  }

  public MetaPartialResponse nextPageUrl(String nextPageUrl) {
    this.nextPageUrl = nextPageUrl;
    return this;
  }

   /**
   * Get nextPageUrl
   * @return nextPageUrl
  **/
  @ApiModelProperty(example = "http://api.facestore.pt/v1/categories?order_by=id%2Cdesc&page=2", value = "")
  public String getNextPageUrl() {
    return nextPageUrl;
  }

  public void setNextPageUrl(String nextPageUrl) {
    this.nextPageUrl = nextPageUrl;
  }

  public MetaPartialResponse path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(example = "http://api.facestore.pt/v1/categories", value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public MetaPartialResponse prevPageUrl(String prevPageUrl) {
    this.prevPageUrl = prevPageUrl;
    return this;
  }

   /**
   * Get prevPageUrl
   * @return prevPageUrl
  **/
  @ApiModelProperty(value = "")
  public String getPrevPageUrl() {
    return prevPageUrl;
  }

  public void setPrevPageUrl(String prevPageUrl) {
    this.prevPageUrl = prevPageUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetaPartialResponse metaPartialResponse = (MetaPartialResponse) o;
    return Objects.equals(this.firstPageUrl, metaPartialResponse.firstPageUrl) &&
        Objects.equals(this.lastPageUrl, metaPartialResponse.lastPageUrl) &&
        Objects.equals(this.nextPageUrl, metaPartialResponse.nextPageUrl) &&
        Objects.equals(this.path, metaPartialResponse.path) &&
        Objects.equals(this.prevPageUrl, metaPartialResponse.prevPageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstPageUrl, lastPageUrl, nextPageUrl, path, prevPageUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetaPartialResponse {\n");
    
    sb.append("    firstPageUrl: ").append(toIndentedString(firstPageUrl)).append("\n");
    sb.append("    lastPageUrl: ").append(toIndentedString(lastPageUrl)).append("\n");
    sb.append("    nextPageUrl: ").append(toIndentedString(nextPageUrl)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    prevPageUrl: ").append(toIndentedString(prevPageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

