/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.I18nProduct;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Product
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T13:53:33.030Z")
public class Product {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("sku")
  private String sku = null;

  @SerializedName("manual")
  private String manual = null;

  @SerializedName("url_video")
  private String urlVideo = null;

  /**
   * Gets or Sets visibility
   */
  @JsonAdapter(VisibilityEnum.Adapter.class)
  public enum VisibilityEnum {
    FACEBOOK("facebook"),
    
    MOBILE("mobile"),
    
    WEBSTORE("webstore"),
    
    NONE("none"),
    
    ALL("all");

    private String value;

    VisibilityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VisibilityEnum fromValue(String text) {
      for (VisibilityEnum b : VisibilityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<VisibilityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VisibilityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VisibilityEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return VisibilityEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("visibility")
  private List<VisibilityEnum> visibility = null;

  @SerializedName("in_homepage")
  private Boolean inHomepage = null;

  @SerializedName("is_prefered")
  private Boolean isPrefered = null;

  @SerializedName("is_digital")
  private Boolean isDigital = null;

  @SerializedName("url_digital")
  private String urlDigital = null;

  @SerializedName("is_new")
  private Boolean isNew = null;

  @SerializedName("i18n")
  private I18nProduct i18n = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("expires_at")
  private OffsetDateTime expiresAt = null;

  public Product id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Product sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @ApiModelProperty(example = "a123b", value = "")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public Product manual(String manual) {
    this.manual = manual;
    return this;
  }

   /**
   * Get manual
   * @return manual
  **/
  @ApiModelProperty(example = "Lorem Ipsum dolus", value = "")
  public String getManual() {
    return manual;
  }

  public void setManual(String manual) {
    this.manual = manual;
  }

  public Product urlVideo(String urlVideo) {
    this.urlVideo = urlVideo;
    return this;
  }

   /**
   * Get urlVideo
   * @return urlVideo
  **/
  @ApiModelProperty(example = "http://youtube.com/foobar/qwocqpeibas2www", value = "")
  public String getUrlVideo() {
    return urlVideo;
  }

  public void setUrlVideo(String urlVideo) {
    this.urlVideo = urlVideo;
  }

  public Product visibility(List<VisibilityEnum> visibility) {
    this.visibility = visibility;
    return this;
  }

  public Product addVisibilityItem(VisibilityEnum visibilityItem) {
    if (this.visibility == null) {
      this.visibility = new ArrayList<VisibilityEnum>();
    }
    this.visibility.add(visibilityItem);
    return this;
  }

   /**
   * channels that resource are showed
   * @return visibility
  **/
  @ApiModelProperty(value = "channels that resource are showed")
  public List<VisibilityEnum> getVisibility() {
    return visibility;
  }

  public void setVisibility(List<VisibilityEnum> visibility) {
    this.visibility = visibility;
  }

  public Product inHomepage(Boolean inHomepage) {
    this.inHomepage = inHomepage;
    return this;
  }

   /**
   * Get inHomepage
   * @return inHomepage
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isInHomepage() {
    return inHomepage;
  }

  public void setInHomepage(Boolean inHomepage) {
    this.inHomepage = inHomepage;
  }

  public Product isPrefered(Boolean isPrefered) {
    this.isPrefered = isPrefered;
    return this;
  }

   /**
   * Get isPrefered
   * @return isPrefered
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isIsPrefered() {
    return isPrefered;
  }

  public void setIsPrefered(Boolean isPrefered) {
    this.isPrefered = isPrefered;
  }

  public Product isDigital(Boolean isDigital) {
    this.isDigital = isDigital;
    return this;
  }

   /**
   * Get isDigital
   * @return isDigital
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isIsDigital() {
    return isDigital;
  }

  public void setIsDigital(Boolean isDigital) {
    this.isDigital = isDigital;
  }

  public Product urlDigital(String urlDigital) {
    this.urlDigital = urlDigital;
    return this;
  }

   /**
   * Get urlDigital
   * @return urlDigital
  **/
  @ApiModelProperty(example = "http://example.com", value = "")
  public String getUrlDigital() {
    return urlDigital;
  }

  public void setUrlDigital(String urlDigital) {
    this.urlDigital = urlDigital;
  }

  public Product isNew(Boolean isNew) {
    this.isNew = isNew;
    return this;
  }

   /**
   * Get isNew
   * @return isNew
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isIsNew() {
    return isNew;
  }

  public void setIsNew(Boolean isNew) {
    this.isNew = isNew;
  }

  public Product i18n(I18nProduct i18n) {
    this.i18n = i18n;
    return this;
  }

   /**
   * Get i18n
   * @return i18n
  **/
  @ApiModelProperty(value = "")
  public I18nProduct getI18n() {
    return i18n;
  }

  public void setI18n(I18nProduct i18n) {
    this.i18n = i18n;
  }

  public Product active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Product createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-10-10T13:26:17+00:00", value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Product updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-10-10T13:26:17+00:00", value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Product expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @ApiModelProperty(example = "2016-10-10T13:26:17+00:00", value = "")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return Objects.equals(this.id, product.id) &&
        Objects.equals(this.sku, product.sku) &&
        Objects.equals(this.manual, product.manual) &&
        Objects.equals(this.urlVideo, product.urlVideo) &&
        Objects.equals(this.visibility, product.visibility) &&
        Objects.equals(this.inHomepage, product.inHomepage) &&
        Objects.equals(this.isPrefered, product.isPrefered) &&
        Objects.equals(this.isDigital, product.isDigital) &&
        Objects.equals(this.urlDigital, product.urlDigital) &&
        Objects.equals(this.isNew, product.isNew) &&
        Objects.equals(this.i18n, product.i18n) &&
        Objects.equals(this.active, product.active) &&
        Objects.equals(this.createdAt, product.createdAt) &&
        Objects.equals(this.updatedAt, product.updatedAt) &&
        Objects.equals(this.expiresAt, product.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sku, manual, urlVideo, visibility, inHomepage, isPrefered, isDigital, urlDigital, isNew, i18n, active, createdAt, updatedAt, expiresAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    manual: ").append(toIndentedString(manual)).append("\n");
    sb.append("    urlVideo: ").append(toIndentedString(urlVideo)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    inHomepage: ").append(toIndentedString(inHomepage)).append("\n");
    sb.append("    isPrefered: ").append(toIndentedString(isPrefered)).append("\n");
    sb.append("    isDigital: ").append(toIndentedString(isDigital)).append("\n");
    sb.append("    urlDigital: ").append(toIndentedString(urlDigital)).append("\n");
    sb.append("    isNew: ").append(toIndentedString(isNew)).append("\n");
    sb.append("    i18n: ").append(toIndentedString(i18n)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

