/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Brand;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.NotFoundResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BrandsApi
 */
@Ignore
public class BrandsApiTest {

    private final BrandsApi api = new BrandsApi();

    
    /**
     * 
     *
     * Creates a new brand in the store.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addBrandsTest() throws ApiException {
        Brand brand = null;
        InlineResponse201 response = api.addBrands(brand);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Deletes a single brand based on the ID supplied
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBrandByIdTest() throws ApiException {
        Long id = null;
        api.deleteBrandById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns a brand based on a single ID  ### Includes You can give the following values on includea parameter: &#x60;routes, products&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBrandByIdTest() throws ApiException {
        Long id = null;
        List<String> includes = null;
        Integer limit = null;
        InlineResponse201 response = api.getBrandById(id, includes, limit);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns all brands from the system that the user has access to  ### Includes You can give the following values on includes parameter: &#x60;routes, products&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBrandsTest() throws ApiException {
        List<String> includes = null;
        Integer limit = null;
        List<String> orderBy = null;
        InlineResponse200 response = api.getBrands(includes, limit, orderBy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update a single brand based on the ID supplied
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCategoryByIdTest() throws ApiException {
        Long id = null;
        Object brand = null;
        api.updateCategoryById(id, brand);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update a single brand based on the ID supplied
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCategoryById_0Test() throws ApiException {
        Long id = null;
        Object brand = null;
        api.updateCategoryById_0(id, brand);

        // TODO: test validations
    }
    
}
