/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2004;
import io.swagger.client.model.InlineResponse2005;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Ignore
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * 
     *
     * Returns all payments from the system that the user has access to 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentByIdTest() throws ApiException {
        Long id = null;
        InlineResponse2005 response = api.getPaymentById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Returns all payments from the system that the user has access to 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentsTest() throws ApiException {
        List<String> includes = null;
        Integer limit = null;
        List<String> orderBy = null;
        InlineResponse2004 response = api.getPayments(includes, limit, orderBy);

        // TODO: test validations
    }
    
}
